version: '3.7'
services:
  jenkins_master:
    image: jenkins/jenkins:2.263.4-lts-centos7
    ports:
      - "8080:8080"
    networks:
      network1:
        ipv4_address: 172.16.1.2
  jenkins_node:
    ports:
      - "2222:22"
    expose:
      - "22"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      network1:
        ipv4_address: 172.16.1.3
    depends_on:
      - jenkins_master

  selenium_hub:
    image: selenium/hub:3.141.59
    expose:
      - "4444"
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=300
    networks:
      network1:
        ipv4_address: 172.16.1.4
  selenium_chrome1:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    expose:
      - "5555"
    ports:
      - "5555:5555"
    networks:
      network1:
        ipv4_address: 172.16.1.5
    environment:
      - HUB_HOST=selenium_hub
      - TZ=CET
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - GRID_BROWSER_TIMEOUT=300
      - NODE_PORT=5555
      - NODE_APPLICATION_NAME=w1

  selenium_chrome2:
    image: selenium/node-chrome-debug:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    expose:
      - "5900"
      - "5556"
    ports:
      - "5900:5900"
      - "5556:5556"
    networks:
      network1:
        ipv4_address: 172.16.1.6
    environment:
      - HUB_HOST=selenium_hub
      - TZ=CET
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - GRID_BROWSER_TIMEOUT=300
      - VNC_NO_PASSWORD=1
      - NODE_PORT=5556
      - NODE_APPLICATION_NAME=w2_debug

networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/16"
